VERSION: 13

# Mysql database setup.
MYSQL-DATABASE:
  ENABLED: false
  SAVE-PERIOD: 5 # The server saves the player statistics for this minute interval to the mysql database.
  CONNECTION:
    HOST: localhost
    PORT: 3306
    DATABASE: zonepractice
    USER: root
    PASSWORD: ""
# Knockback modifier - it very much depends on the hit delay. You should test what is the optimal for you.
KNOCKBACK:
  NORMAL:
    AIR-HORIZONTAL: 0.93
    AIR-VERTICAL: 0.93
    HORIZONTAL: 0.82
    VERTICAL: 0.88
  COMBO:
    AIR-HORIZONTAL: 2.8
    AIR-VERTICAL: 2.8
    HORIZONTAL: 2.5
    VERTICAL: 2.5
#
# Queue settings
QUEUE:
  UNRANKED:
    MAX-QUEUE-TIME: 300 # In sec.
    DIVISION-SEARCH:
      ENABLED: true
      SETTINGS:
        SEARCH-IN-OWN-DIVISIONS: 20 # In sec.
        EXTEND-DIVISION-SEARCH: 10 # In sec.
    SELECTOR-GUI:
      SHOW-DISABLED-LADDERS: true
      FIRST-CATEGORY:
        SIZE: 4
        GO-TO-SECOND-CATEGORY-SLOT: 35
        LADDERS:
          BATTLERUSH: 10
          BEDWARS: 11
          BOXING: 12
          BRIDGES: 14
          FIREBALL: 15
          GAPPLE: 16
          NODEBUFF: 20
          COMBO: 21
          SUMO: 22
          BUILDUHC: 23
          PEARLFIGHT: 24
      SECOND-CATEGORY:
        ENABLED: true
        BACK-TO-FIRST-CATEGORY-SLOT: 35
        SIZE: 4
        LADDERS:
          ARCHER: 10
          AXE: 11
          DEBUFF: 12
          SG: 14
          SKYWARS: 15
          SOUP: 16
          SPLEEF: 20
          VANILLA: 24
  RANKED:
    MAX-QUEUE-TIME: 300 # In sec.
    DEFAULT-ELO: 1000
    ELO-RANGE-TIME: 5 # Sec
    ELO-RANGE-INCREASE: 20 # Range
    ELO-CHANGE: 5-12 # Players receive a random elo between these two numbers.
    MAX-PING: 300 # Maximum ping a player can join a ranked queue.
    SELECTOR-GUI:
      SHOW-DISABLED-LADDERS: true
      FIRST-CATEGORY:
        SIZE: 4
        GO-TO-SECOND-CATEGORY-SLOT: 35
        LADDERS:
          BATTLERUSH: 10
          BEDWARS: 11
          BOXING: 12
          BRIDGES: 14
          FIREBALL: 15
          GAPPLE: 16
          NODEBUFF: 20
          COMBO: 21
          SUMO: 22
          BUILDUHC: 23
          PEARLFIGHT: 24
      SECOND-CATEGORY:
        ENABLED: true
        BACK-TO-FIRST-CATEGORY-SLOT: 18
        SIZE: 3
        LADDERS:
          DEBUFF: 11
          SG: 12
          SKYWARS: 13
          SOUP: 14
          SPLEEF: 15
#
# Admin settings
ADMIN-SETTINGS:
  OP-BYPASS-ELO-CHANGE: true # If true, op players ladder elo's cannot be changed by commands.
  OP-BYPASS-UNRANKED-CHANGE: true # If true, commands cannot change op players' daily unranked limit.
  OP-BYPASS-RANKED-CHANGE: true # If true, commands cannot change op players daily ranked limit.
  OP-BYPASS-EXP-CHANGE: true # If true, commands cannot change op players' experience.
  OP-BYPASS-INFOGUI: true # If true, op players info gui can only be opened by themselves.
  OP-BYPASS-FULL-RESET: true # If true, they can only reset op players themselves.
#
# Auto save settings
#
# It basically doesn't affect the server performance since it happens async.
AUTO-SAVE:
  ENABLED: true # It is recommended to enable this, as the plugin is only saved during automatic backups and when the server is shut down. If it crashes and auto-save is disabled, all progress will be lost.
  ALERT: true
  INTERVAL: 10 # minutes
#
# Match settings
MATCH-SETTINGS:
  TEAMS:
    TEAM1:
      NAME: "<blue>[B]"
      COLOR: "<blue>"
      NAMETAG:
        PREFIX: ""
        NAME-COLOR: BLUE
        SUFFIX: ""
    TEAM2:
      NAME: "<red>[R]"
      COLOR: "<red>"
      NAMETAG:
        PREFIX: ""
        NAME-COLOR: RED
        SUFFIX: ""
    FFA:
      COLOR:
        "<yellow>"
  MATCH-TYPE-NAMES:
    DUEL: "&e&lDuel"
    PARTY_FFA: "&e&lParty FFA"
    PARTY_SPLIT: "&e&lParty Split"
    PARTY_VS_PARTY: "&e&lParty Vs Party"
  WEIGHT-CLASS:
    UNRANKED: "&aUnranked"
    RANKED: "&cRanked"
  LEAVE-COMMAND:
    ENABLED: true
    WEIGHT-CLASS:
      UNRANKED: true
      RANKED: false
  END-COMMAND:
    DUEL:
      UNRANKED:
        WINNER-COMMANDS:
          - ""
        LOSER-COMMANDS:
          - ""
      RANKED:
        WINNER-COMMANDS:
          - ""
        LOSER-COMMANDS:
          - ""
  START-COMMAND:
    LADDER_NAME: # like GAPPLE etc. always write with upper case
      MATCH:
        - ""
      ROUND:
        - ""
  MATCH-STATISTIC:
    REMOVE-AFTER: 60 # After the seconds, the players won't be able to open their match statistics.
  BUILD-LIMIT-DEFAULT: 4 # Counts from the first players positions Y level. You can set a unique number for this for every arena, then it will consider where you are standing.
  AFTER-COUNTDOWN: 3 # After the match is over this countdown start, and when it's over, the players teleport back to the lobby.
  GOLDEN-HEAD: # Golden head settings.
    ITEM:
      NAME: "&e&lGolden Head"
      MATERIAL: GOLDEN_APPLE
      DAMAGE: 1
      LORE:
        - ""
        - "&7This apple gives you extra"
        - "&7health and effects."
        - ""
    #
    # You can add any potion effects for the golden head.
    # But it has to follow a strict format like below:
    # POTION_TYPE::DURATION_IN_SECONDS::STRENGTH
    # You can find the potion types in here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
    EFFECTS:
      - "ABSORPTION::90::1"
      - "REGENERATION::20::2"
  REMOVE-EMPTY-BOTTLE: true # Removes empty potion bottles after the player use it.
  DUEL:
    INVITATION-EXPIRY: 60 # After the seconds, the duel request will expire.
    ROUND-SELECTOR:
      MAX: 10
      MIN: 1 # Can't be lower than 1.
  ENDERPEARL:
    COOLDOWN: 13 # This is the default cooldown. You can change it in the ladder settings.
    EXP-BAR: true # Countdown shows on exp bar.
  FIREBALL-FIGHT: # These are multiplier values, so please test what is optimal for you and don't change them too much at once or the difference will multiply.
    FIREBALL-SPEED: 1.3
    FIREBALL-YIELD: 2
    EXPLOSION:
      TNT:
        HORIZONTAL: 1.9
        VERTICAL: 2.1
      FIREBALL:
        HORIZONTAL: 1.9
        VERTICAL: 2.1
  BOXING:
    CUSTOM-ATTACK-COOLDOWN:
      ENABLED: true
      COUNT-FROM: 0.8 # 0.0-1.0 value
      ONLY-SWORD: true
  PARTY:
    SPLIT-TEAM-DAMAGE: false # In party split games, players with the same team can't hurt each other (if false).
    PARTY-VS-PARTY-TEAM-DAMAGE: false # In party vs party games, players with the same party can't hurt each other (if false).
  REMATCH: # Players get an item in their lobby inventory after duels, so they can easily request a rematch.
    ENABLED: true
    EXPIRE-TIME: 20 # sec
  KIT-ITEMS:
    DEFAULT-KIT:
      NAME: "&e&lDefault Kit"
      MATERIAL: ENCHANTED_BOOK
    CUSTOM-KIT:
      NAME: "&a&lKit %kit%"
      MATERIAL: ENCHANTED_BOOK
  LADDER-SETTINGS:
    BRIDGE:
      REGENERATING-ARROW:
        ENABLED: true
        EXP-BAR: true
        TIME: 5 # In sec.
  DISPLAY-ARROW-HIT-HEALTH: true # If true, the player will see the health of the player they hit.
#
# FFA settings
FFA:
  ROLLBACK:
    SECONDS: 300 # After the seconds, the arena will be reseted back to its original state (only on build arenas).
  DISPLAY-ARROW-HIT-HEALTH: true # If true, the player will see the health of the player they hit.
  ENDER-PEARL-EXP-BAR: true # If true, the ender pearl cooldown will be displayed on the exp bar.
  ALLOW-DESTROYABLE-BLOCK: true # If true, player can destroy the fixed blocks in the arena that their ladder has.
  ENABLE_TNT: true # If true, players can use TNT in the arena (ONLY IN BUILD MODE).
#
# Spectator settings
SPECTATOR-SETTINGS:
  SPECTATOR-MODE: true # If false, player can't use spectator mode, only watch single matches.
  SPECTATOR-MENU: true # Turn on/off the spectator menu.
  VANISH-COOLDOWN: 5 # Between vanish toggles this many seconds has to pass.
  RANDOM-MATCH-COOLDOWN: 10 # Between random match searches, this many seconds has to pass.
  SPECTATOR-SPEED: 2 # The spectators flying speed. Between 1 and 10
#
# Party settings
PARTY:
  SETTINGS:
    MAX-PARTY-MEMBERS:
      DEFAULT: 6 # Maximum party members, if the owner doesn't have permission to change it.
      PERMISSION: 20 # The maximum limit the party leader can set for the party.
    DEFAULT:
      PUBLIC-PARTY: false
      ALL-INVITE: false
      PARTY-CHAT: true
      DUEL-REQUESTS: true
  PUBLIC-BROADCAST-TIME: 20 # The party will be advertised at these intervals (seconds).
  BROADCAST-TIMES: 5 # This many times the party will broadcast in the chat.
  PARTY-INVITE-COOLDOWN: 60 # After these seconds, the party invite will expire.
  REQUEST-EXPIRY: 60 # After the seconds the party vs party request will expire.
  END-MATCH-ON-DISBAND: true # If the party is disbanded, the ongoing match will end.
#
# Staff mode
STAFF-MODE:
  JOIN-HIDE-FROM-PLAYERS: false # When a staff joins, the server instantly hides them from other players.
  STAFF-SPECTATOR-SPEED: 2 # Staff mode spectation flying speed.
#
# Sounds - You can find the sound list here: https://helpch.at/docs/1.20.3/org/bukkit/Sound.html
SOUNDS:
  MATCH_START_COUNTDOWN:
    ENABLED: true
    SOUND: BLOCK_NOTE_BLOCK_PLING
    VOLUME: 1
    PITCH: 1
  MATCH_STARTED:
    ENABLED: true
    SOUND: ENTITY_PLAYER_LEVELUP
    VOLUME: 1
    PITCH: 1
  BED_BREAK:
    ENABLED: true
    SOUND: ENTITY_ENDER_DRAGON_GROWL
    VOLUME: 1
    PITCH: 1
  MATCH_PLAYER_TEMP_DEATH: # When a bed fight player dies in a match while he still has his bed.
    ENABLED: true
    SOUND: ENTITY_PLAYER_LEVELUP
    VOLUME: 1
    PITCH: 1
  MATCH_PLAYER_DEATH:
    ENABLED: true
    SOUND: ENTITY_BLAZE_DEATH
    VOLUME: 1
    PITCH: 1
  TOTEM_SAVE_PLAYER:
    ENABLED: true
    SOUND: ITEM_TOTEM_USE
    VOLUME: 1
    PITCH: 1
#
# Leaderboard settings
LEADERBOARD:
  HOLOGRAM:
    DYNAMIC-UPDATE: 10 # Sec. This type of hologram is switching between ladders.
    STATIC-UPDATE: 30 # Sec. This type of hologram is always show one ladder or global elo stats.
    FORMAT: # Also placeholders: %division%, %division_short%, %group%, %ladder_name%
      NULL-LINE: "&6%number%. &cN/A"
      NOTHING-TO-DISPLAY: "&cThere is nothing to display."
      ELO:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6ELO Top"
            - "%top%"
          LADDER:
            - "&6ELO Top &7- &e%ladder_displayName%"
            - "%top%"
      WIN:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Win Top"
            - "%top%"
          LADDER:
            - "&6Win Top &7- &e%ladder_displayName%"
            - "%top%"
      KILLS:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Kill Top"
            - "%top%"
          LADDER:
            - "&6Kill Top &7- &e%ladder_displayName%"
            - "%top%"
      DEATHS:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Deaths Top"
            - "%top%"
          LADDER:
            - "&6Deaths Top &7- &e%ladder_displayName%"
            - "%top%"
      WIN_STREAK:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Win Streak Top"
            - "%top%"
          LADDER:
            - "&6Win Streak Top &7- &e%ladder_displayName%"
            - "%top%"
      BEST_WIN_STREAK:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Best Win Streak Top"
            - "%top%"
          LADDER:
            - "&6Best Win Streak Top &7- &e%ladder_displayName%"
            - "%top%"
      LOSE_STREAK:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Lose Streak Top"
            - "%top%"
          LADDER:
            - "&6Lose Streak Top &7- &e%ladder_displayName%"
            - "%top%"
      BEST_LOSE_STREAK:
        TITLE-LINE-SPACING: 0.5
        LINE-SPACING: 0.3
        FORMAT: "&6%placement%. %division% | %player%&8: &e%score%"
        LINES:
          GLOBAL:
            - "&6Best Lose Streak Top"
            - "%top%"
          LADDER:
            - "&6Best Lose Streak Top &7- &e%ladder_displayName%"
            - "%top%"
      SETUP-HOLO:
        TITLE: "&cThis hologram must be set."
        LINE: "&6Hologram Name: &e%name%"
#
# Sidebar settings
SIDEBAR:
  UPDATE-TIME: 20 # In ticks. 20 ticks = 1 second
#
# Arena settings
ARENA:
  LOAD-CHUNKS: true # If true, the server will load the enabled arena's chunks.
  TELEPORT-TO-COPY: false # Recommend: false,  If you copy an arena, the server will teleport you there, so you can watch it happening.
  FAST-COPY: false # If true, the server more likely to be slow, but it triples the copy performance. 100x50x65 arena copy takes 1,5 minutes with fast copy.
  DEFAULT-ICON: # If default icon is enabled it won't be necessary to set an arena icon, but you still can.
    ENABLED: false
    ICON:
      NAME: "&6%arena%"
      MATERIAL: FIREWORK_STAR
      # DAMAGE: 4 # You can set the damage to the material as well.
#
# Event settings
EVENT:
  MULTIPLE: false # If true, multiple events can happen in the same time. But only one can be in the collecting phase.
  AUTO-EVENTS: true
  ENDERPEARL-COOLDOWN: 10 # In sec.
  BROADCAST:
    ENABLE: true
    MESSAGE-TO:
      IN-PARTY: true # If true and the player is a member of a party, he will receive the broadcast message.
      IN-UNRANKED-MATCH: true # If true and the player is in an unranked match, he will receive the broadcast message.
      IN-RANKED-MATCH: false # If true and the player is in a ranked match, he will receive the broadcast message.
      IN-EVENT: true # If true and the player is in another event, he will receive the broadcast message.
  PLAYER-TRACKER: # Shows the nearest player.
    NAME: "&cPlayer Tracker &7(Right-Click)"
    MATERIAL: COMPASS
  LMS: # Please be aware that building is not yet supported for the event.
    NAME: "LMS"
    SETTINGS:
      DROP-INVENTORY: true # If a player dies, drop his inventory.
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
    AUTO-EVENTS: # At this time of the day an automatic lms event is going to start. You can extend the list, and add it to other events as well. If you have any question about this, please join the discord server.
      - "18:30"
  OITC:
    NAME: "OITC"
    SETTINGS:
      PLAYER-LIFE: 5 # Every player gets this many lives. When they die, they loose 1 life.
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
      - "eco give %player% 10"
  TNTTAG:
    NAME: "TNT Tag"
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
    TAGGED-ITEM:
      NAME: "&cYou're IT, tag someone!"
      MATERIAL: TNT
  BRACKETS: # Please be aware that building is not yet supported for the event.
    NAME: "Brackets"
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
  SUMO:
    NAME: "Sumo"
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
  SPLEGG: # Please be aware that building is not yet supported for the event.
    NAME: "Splegg"
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
    EGG-LAUNCHER-ITEM:
      NAME: "&aShoot The Blocks &7(Right-Click)"
      MATERIAL: IRON_SHOVEL
  JUGGERNAUT: # Please be aware that building is not yet supported for the event.
    NAME: "Juggernaut"
    WINNER-COMMAND:
      - "practice ranked add %player% 3"
#
# Player settings
PLAYER:
  DELETE-INACTIVE-USER:
    ENABLED: true
    DAYS: 30 # After this number of days, the inactive player profiles will be deleted.
  SETTINGS-DELAY: 3 # Sec between settings can be changed. It can be bypassed.
  LOBBY-NAMETAG:
    ENABLED: true
  JOIN-TELEPORT-LOBBY: true # If true, the player will be teleported to the lobby when they join the server.
  GROUP-CHAT:
    ENABLED: true # If enabled, the player's chat will be formatted by their group. It is only viable if "SERVER-CHAT" is also enabled.
  DEFAULT-SETTINGS:
    DUELREQUEST: true
    SIDEBAR: true
    HIDEPLAYERS: false
    PARTYINVITES: true
    ALLOWSPECTATE: true
    PRIVATEMESSAGE: true
    FLYING: false
    WORLD-TIME: DAY # Options: SUNRISE, DAY, SUNSET, NIGHT
#
# Division settings
DIVISIONS:
  ENABLED: true
  NEW-DIVISION-MESSAGE: true
  MIN-DIVISION-FOR-RANKED: SILVER2 # Have to give the config name, not the full name
#
# Chat settings
CHAT:
  SERVER-CHAT-ENABLED: true
  PARTY-CHAT-ENABLED: true
  STAFF-CHAT:
    ENABLED: true
    SHORTCUT: true # If true, you can use send message like #hello world instead of enabling staff chat each time.
  PRIVATE-CHAT-ENABLED: true # Private message system /message (/m) and /reply (/re, /r)
#
# Tab list
TAB-LIST:
  ENABLED: true
  UPDATE: 5 # In sec.
  HEADER:
    - "<gray>-------------------"
    - "<gold>ZonePractice <gray>Pro"
    - "<gray>-------------------"
  FOOTER:
    - "<gray>-------------------"
    - "<red>nandi0813.hu"
    - "<gray>-------------------"